name: Tests-Check

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone master branch
        uses: actions/checkout@v2
      - name: Test core
        run: go test -run ./tests/core_test.go
      - name: Test cli
        run: go test -run ./tests/cli_test.go

